runtime: python39
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*\.md)
  static_files: \1
  upload: (.*\.md)
- url: /(.*\.(css|png|jpg|jpeg|gif|svg))
  static_files: \1
  upload: (.*\.(css|png|jpg|jpeg|gif|svg))
